url: http://aleph.rs
markdown: kramdown
permalink: pretty
sass:
  sass_dir: css
  style: compressed

# Opsti podaci
title:  Aleph
name:   Aleph
description: Obuka iz veb programiranja
contact_email:  vpobuka@gmail.com
contact_addr:   Bulevar Mihajla Pupina 4a
contact_city:   Novi Sad
contact_desc:   'Zgrada Univerziteta Singidunum'

# Boje
color:
  primary: ec7263
  secondary: ec7263  
  secondary-dark: 333

# Imena, slike i biografije predavača:
people:
- name: Milan Segedinac
  pic:  milan_segedinac.jpg
  bio:  'Dr Milan Segedinac je docent na Fakultetu tehničkih nauka. Od 2009. godine učestvuje u održavanju nastave na Fakultetu tehničkih nauka, kroz šta je stekao iskustvo u obrazovnom radu. Oblasti naučnog interesovanja su mu Semantički Web i Elektronski podržano učenje i autor je preko trideset naučnih radova. Pored angažovanja u nastavi i u načuno-istraživačkim projektima, od 2008. godine učestvovao je u realizaciji preko deset komercijalnih projekata kao senior programer, team leader i sistem arhitekta.'

- name: Goran Savić
  pic:  goran_savic.jpg
  bio:  'Dr Goran Savić je docent na Fakultetu tehničkih nauka. Iskustvo u nastavnom radu ima od 2008. godine od kada učestvuje u održavanju nastave na Fakultetu tehničkih nauka. Oblasti naučnog interesovanja su mu Web development i Elektronski podržano učenje i autor je preko trideset naučnih radova. Pored angažovanja u nastavi i naučno-istraživačkim projektima, od 2007. godine učestvovao je u realizaciji preko deset komercijalnih projekata kao senior programer, vođa tima i sistem arhitekta.'

  
# Tok produzene obuke
lessonflow:
- text: 'Početak uvodnog modula (septembar 2017.)'  
  icon: fa-circle  

- text: ''
  icon: fa-long-arrow-down

- text: 'Proceduralno programiranje'
  description: 'Tipovi i strukture podataka, kontrola toka programa, funkcije, algoritmi, ulazno-izlazni podsistem - programski jezik Java'
  icon: fa-keyboard-o

- text: ''
  icon: fa-long-arrow-down

- text: 'Objektno programiranje'
  description: 'Osnovni koncepti objektnog programiranja, veze između klasa, nasleđivanje, polimorfizam, objektno modelovanje, UML i dizajn šabloni – programski jezik Java'
  icon: fa-puzzle-piece

- text: ''
  icon: fa-long-arrow-down

- text: 'Baze podataka'
  description: 'Osnovni koncepti relacionih baza podataka, Modelovanje baza podataka - programski jezik SQL'
  icon: fa-database

- text: ''
  icon: fa-long-arrow-down

- text: 'Osnove veba'
  description: 'HTTP protokol, statički i dinamički elementi veb stranica - HTML, CSS, JavaScript'
  icon: fa-globe

- text: ''
  icon: fa-long-arrow-down

- text: 'Početak naprednog modula (februar 2018.)'
  icon: fa-circle

- text: ''
  icon: fa-long-arrow-down

- text: 'Alati za upravljanje projektom'
  description: 'Upravljanje verzijama i timski rad - Git, Izgradnja aplikacije - Maven, npm'
  icon: fa-space-shuttle

- text: 'Serverski deo veb aplikacija'
  description: 'Spring radni okvir, objektno-relaciono mapiranje - JPA specifikacija, REST servisi'
  icon: fa-leaf

- text: ''
  icon: fa-long-arrow-down

- text: 'Klijentski deo veb aplikacija'
  description: 'Rukovanje stablom HTML stranice, asinhroni pozivi, napredno JavaScript programiranje – biblioteka jQuery, radni okvir Angular'
  icon: fa-code

- text: ''
  icon: fa-long-arrow-down

- text: 'Završni test'
  description: 'Na kraju obuke se organizuje završni ispit, koji obuhvata celokupno gradivo kursa. Po završetku obuke se polaznicima dodeljuje sertifikat o pohađanju ili uspešno završenoj obuci, u zavisnosti od rezultata ostvarenih na završnom ispitu. Kurs je uspešno završen, ako polaznik na završnom ispitu ostvari najmanje 50% bodova.'
  icon: fa-star

# Partners
partners:
- name: Levi9
  url: https://www.levi9.com
  logo: levi9.jpg

- name: Execom
  url: https://www.execom.eu/
  logo: execom.jpg

- name: Vivify Ideas
  url: http://www.vivifyideas.com/
  logo: vivify.jpg

- name: EXLRT
  url: http://www.exlrt.com/
  logo: exlrt.jpg

- name: IT Engine
  url: http://www.itengine.rs/
  logo: itengine.jpg

- name: ComData
  url: http://www.comdata.rs/
  logo: comdata.jpg

- name: M&I Systems, Co.
  url: http://www.mi-system.co.rs/
  logo: mandi.jpg

- name: TIAC group
  url: http://www.tiacgroup.com/
  logo: tiac.png